#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/LXY1226/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: NEWIFI3
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config #smartdns
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> .config #smartdns二进制文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=y" >> .config #Socks5服务器
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n" >> .config #`openssl`
        sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_QOS=n" >> .config # QoS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_EAP_PEAP/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_EAP_PEAP=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSH=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SFTP/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_SFTP=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DROPBEAR/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_DROPBEAR=y" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DROPBEAR_FAST_CODE/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_DROPBEAR_FAST_CODE=y" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XFRM/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_XFRM=y" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=y" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_XUPNPD=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_LRZSZ=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #zerotier ~1.3M
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
